site_name: Amper
site_url: https://jetbrains.github.io/amper

docs_dir: src

repo_name: amper
repo_url: https://github.com/JetBrains/amper

site_description: "An experimental build tool for the Kotlin and Java languages, with a focus on UX and tooling."
site_author: JetBrains Amper team

theme:
  name: material
  logo: images/amper-logo.svg
  favicon: images/amper-logo.svg
  features:
    - content.code.copy
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search
  - macros # for variable substitution in Markdown files

markdown_extensions:
  - abbr # for abbreviation tooltips
  - admonition # for info/warn/tip/... sections
  - attr_list # required for attribute-based features (grid, alignment, buttons, tooltips, etc.)
  - def_list # for definition lists (stomp config)
  - footnotes
  - pymdownx.details # for collapsible admonitions
  - pymdownx.emoji # for emoji shortcuts with :name: syntax
  - pymdownx.highlight # for syntax highlighting in code blocks
  - pymdownx.inlinehilite # for inline code highlighting
  - pymdownx.superfences # required for code highlighting, tabs, and nested content in general
  - pymdownx.tabbed # for tabs support
  - tables
  - toc:
      permalink: true

nav:
  - 'Overview': index.md
  - 'Documentation': documentation.md
  - 'Setup': setup.md
  - 'Tutorial': tutorial.md
  - 'Usage': usage.md
  - 'DSL Reference': dsl-reference.md
  - 'FAQ': faq.md
  - 'Releases ðŸ¡•': https://github.com/JetBrains/amper/releases

extra:
  # The git_branch variable is used to generate the repo_filetree_url variable to link to repo files from the docs.
  # The BUILD_BRANCH variable is provided by the CI when building the docs.
  # The HEAD fallback is to avoid breaking links locally.
  git_branch: !ENV [BUILD_BRANCH, "HEAD"]
  version:
    provider: mike # enables the version selector

copyright: Copyright &copy; 2000-2025 JetBrains s.r.o. and contributors
