site_name: Amper
site_description: "An experimental build tool for the Kotlin and Java languages, with a focus on UX and tooling."
site_url: https://amper.org
site_author: JetBrains Amper team

repo_name: JetBrains/amper
repo_url: https://github.com/JetBrains/amper
edit_uri: !ENV [MKDOCS_GIT_EDIT_URL, "edit/HEAD/docs/src/"]

copyright: Copyright &copy; 2000-2025 JetBrains s.r.o. and contributors

# The default place for Markdown "source" files for the docs is "docs/", but that would result in docs/docs/ for us
docs_dir: src

theme:
  name: material
  logo: images/amper-icon.svg
  favicon: images/amper-icon.svg
  font:
    code: JetBrains Mono
  features:
    - content.action.edit # adds an "Edit this page" button to each page
    - content.code.annotate # allows annotations (tooltips) inside code blocks
    - content.code.copy # adds a copy button to code blocks
    - navigation.expand # makes the navigation sections collapsible
    - navigation.footer # for next/prev links at the bottom of each page
    - navigation.indexes # to be able to associate a Markdown file with the "root" of a section without a nested page
    - navigation.instant # to use XHR instead of reloading the page when following links
    - navigation.tabs # turns the top-level navigation sections into tabs in the header bar
    - navigation.top # adds a back-to-top button when scrolling up after scrolling down on a page
    - navigation.tracking # updates the URL bar with anchors as the user scrolls
    - search.highlight # highlights the search term in the target page when clicking a search result
    - search.share # allows deep linking to search results
    - search.suggest # enables completion in the search bar
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - macros # for variable substitution in Markdown files
  - git-revision-date-localized: # to have the "last update" date in the footer of each page
      enabled: !ENV [CI, false] # we don't put the whole repo in the docker container locally, so there is no git repo
  - git-committers: # to have the list of authors of the page
      enabled: !ENV [CI, false] # we don't put the whole repo in the docker container locally, so there is no git repo
      repository: JetBrains/amper
      branch: !ENV [MKDOCS_GIT_BRANCH, "HEAD"]
      token: !ENV [MKDOCS_COMMITTERS_PLUGIN_GITHUB_TOKEN, ""]
  - search
  - social # for proper previews in social media links

markdown_extensions:
  - abbr # for abbreviation tooltips
  - admonition # for info/warn/tip/... sections
  - attr_list # required for attribute-based features (grid, alignment, buttons, tooltips, etc.)
  - def_list # for definition lists (stomp config)
  - footnotes
  - md_in_html # to process Markdown inside HTML (useful for grids)
  - pymdownx.details # for collapsible admonitions
  - pymdownx.emoji: # for emoji shortcuts with :name: syntax
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - .icons
  - pymdownx.highlight # for syntax highlighting in code blocks
  - pymdownx.inlinehilite # for inline code highlighting
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md # auto-append abbreviations.md to all pages to get the definitions on hover
  - pymdownx.superfences # required for code highlighting, tabs, and nested content in general
  - pymdownx.tabbed: # for tabs support
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify # use the tab name in URL anchor instead of '__tabbed_1_1'
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: true

watch:
  - .icons
  - includes

nav:
  - 'Home': index.md
  - 'Getting started':
      - getting-started/index.md
      - 'IDE setup': getting-started/ide-setup.md
      - 'Tutorial': getting-started/tutorial.md
      - 'Amper CLI': getting-started/cli.md
  - 'User guide':
      - user-guide/index.md
      - 'Basic concepts': user-guide/basics.md
      - 'Dependencies': user-guide/dependencies.md
      - 'Multiplatform modules': user-guide/multiplatform.md
      - 'Testing': user-guide/testing.md
      - 'Templates': user-guide/templates.md
      - 'Built-in technologies':
          - 'Android': user-guide/builtin-tech/android.md
          - 'Compose Multiplatform': user-guide/builtin-tech/compose-multiplatform.md
          - 'iOS': user-guide/builtin-tech/ios.md
          - 'Kotlin Serialization': user-guide/builtin-tech/kotlin-serialization.md
          - 'Ktor': user-guide/builtin-tech/ktor.md
          - 'Lombok': user-guide/builtin-tech/lombok.md
          - 'Spring Boot': user-guide/builtin-tech/spring.md
      - 'Advanced topics':
          - 'Java annotation processing': user-guide/advanced/java-annotation-processing.md
          - 'Kotlin Symbol Processing (KSP)': user-guide/advanced/ksp.md
          - 'Kotlin compiler plugins': user-guide/advanced/kotlin-compiler-plugins.md
          - 'Maven-like layout': user-guide/advanced/maven-like-layout.md
      - 'Appendix: YAML primer': user-guide/yaml-primer.md
  - 'Reference':
    - 'project.yaml': reference/project.md
    - 'module.yaml': reference/module.md
  - 'FAQ': faq.md
  - 'Releases â†—': https://github.com/JetBrains/amper/releases

extra:
  # The git_branch variable is used to generate the repo_filetree_url variable to link to repo files from the docs.
  # The MKDOCS_GIT_BRANCH variable is provided by the CI when building the docs.
  # The HEAD fallback is to avoid breaking links locally.
  git_branch: !ENV [MKDOCS_GIT_BRANCH, "HEAD"]
  version:
    provider: mike # enables the version selector

validation:
  absolute_links: warn
  anchors: warn
  omitted_files: warn
  unrecognized_links: warn
